### PR TITLE
xonda v0.8.0

### PR DESCRIPTION
**Pull request by gforsyth**
Merge only after success.

This pull request was auto-generated by [rever](https://regro.github.io/rever-docs/)

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
Does xonda 0.8.0 require xonsh>=0.8.0 ?

**Comment by gforsyth** [comment]
Oh yeah, it definitely does.

**Comment by gforsyth** [comment]
Thanks for spotting that @mariusvniekerk !

**Comment by gforsyth** [comment]
Closed in favor of #6

**Pull request closed without merging**
